name = "ACE1x"
uuid = "5cc4c08c-8782-4a30-af6d-550b302e9707"
authors = ["Christoph Ortner <christohortner@gmail.com> and contributors"]
version = "0.1.11"

[deps]
ACE1 = "e3f9bc04-086e-409a-ba78-e9769fe067bb"
ACEbase = "14bae519-eb20-449c-a949-9c58ed33163e"
JuLIP = "945c410c-986d-556a-acb1-167a618e0462"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RepLieGroups = "f07d36f2-91c4-427a-b67b-965fe5ebe1d2"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
ACE1 = "0.11.14, 0.12.0"
RepLieGroups = "0.0.1, 0.0.2, 0.0.3"
julia = "1.9, 1.10"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Printf"]
